### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by Upbeatbobcat36** [k2fc/scope#10]
Hey, 

I tried to install and build the program in visual studio and I didn’t have any luck. It would be amazing if someone could help me get this running.

**Comment by Oxillius** [comment]
Review [this repository](https://github.com/Oxillius/scope-profiles) for help. The linked repository has pre-made profiles only for ZMA and ZJX TRACONs but you could use these to create other TRACONs.

**Comment by nycmadu** [comment]
Hey @Oxillius, I've notice that "https://dstars.graiani.com/dstars/JAX" does not update anymore with ADSB. I believe this goes for the all the XMls I currently have. I wanted to host one of them on a local machine. Is this data from FAA swim SFDPS? In a format like

"{"Source":0,"Altitude":{"Value":100,"AltitudeType":1},"GroundSpeed":1,"GroundTrack":45,"Ident":false,"IsOnGround":false,"Squawk":"1200","VerticalRate":0,"ModeSCode":11413774,"UpdateType":0,"Guid":"b8d4c6c4-581c-4fee-bb9c-7191af75f1d5","TimeStamp":"2024-02-21T15:28:16.3625156+00:00"}"

Do you have any advice or help making this possible?

**Comment by madu12435** [comment]
> Hey,
> 
> I tried to install and build the program in visual studio and I didn’t have any luck. It would be amazing if someone could help me get this running.

I build it Visual Solutions since the .SLN is provided. You will also need to install Csharp Metar Decoder.

**Comment by Oxillius** [comment]
> Hey @Oxillius, I've notice that "https://dstars.graiani.com/dstars/JAX" does not update anymore with ADSB. I believe this goes for the all the XMls I currently have. I wanted to host one of them on a local machine. Is this data from FAA swim SFDPS? In a format like
> 
> "{"Source":0,"Altitude":{"Value":100,"AltitudeType":1},"GroundSpeed":1,"GroundTrack":45,"Ident":false,"IsOnGround":false,"Squawk":"1200","VerticalRate":0,"ModeSCode":11413774,"UpdateType":0,"Guid":"b8d4c6c4-581c-4fee-bb9c-7191af75f1d5","TimeStamp":"2024-02-21T15:28:16.3625156+00:00"}"
> 
> Do you have any advice or help making this possible?

https://dstars.graiani.com/dstars/### is now working. The servers are back up and returning data.

**Comment by nycmadu** [comment]
> > Hey @Oxillius, I've notice that "https://dstars.graiani.com/dstars/JAX" does not update anymore with ADSB. I believe this goes for the all the XMls I currently have. I wanted to host one of them on a local machine. Is this data from FAA swim SFDPS? In a format like
> > "{"Source":0,"Altitude":{"Value":100,"AltitudeType":1},"GroundSpeed":1,"GroundTrack":45,"Ident":false,"IsOnGround":false,"Squawk":"1200","VerticalRate":0,"ModeSCode":11413774,"UpdateType":0,"Guid":"b8d4c6c4-581c-4fee-bb9c-7191af75f1d5","TimeStamp":"2024-02-21T15:28:16.3625156+00:00"}"
> > Do you have any advice or help making this possible?
> 
> https://dstars.graiani.com/dstars/### is now working. The servers are back up and returning data.

I understand but do you know how it was setup with FAA swim data was it TFMS? I wana try hosting it myself but don't know what swim client was used?
