### ISSUE TITLE
Formation Targets

### ISSUE THREAD

**Issue by zladatm** [k2fc/scope#12]
I _think_ but am not totally sure that the STARS emulation isn't sure what to do with SWIM data that refers to formation targets. There's a commemorative T38 squadron that regularly flies out of VNY that only shows up in the program when they are squawking 1200. My theory is that the formation formatted data tag isn't being processed.

**Comment by k2fc** [comment]
I'd imagine if they are military, they would be excluded from the data feed.  Do you have a date/time I can look at?

**Comment by zladatm** [comment]
KVNY on 2024-05-27 1707:30z N3169G departs VNY southbound to eastbound, it end up part of a formation. It's the aircraft I was thinking of when I wrote the comment. That aircraft participates in a lot of formation work if you need a more recent example.

**Comment by k2fc** [comment]
N3169G is blocked from tracking.  See: https://www.flightaware.com/live/flight/N3169G
