### ISSUE TITLE
Radar Collection/Sweep Times

### ISSUE THREAD

**Issue by avoflight** [k2fc/scope#6]
I apologize as I am probably misunderstanding something, but is Date/Time Radar Collection Editor and Sweep Times allow for a playback option, or is this entirely something different? 
Regardless I have attempted experimenting with the settings and doesn't seem to change on the scope..?

Super appreciate your guys' work, I would love to give back and donate in the future. 

- M

**Comment by k2fc** [comment]
There is no ability for playback currently

**Comment by avoflight** [comment]
Figured as much, appreciate it!
